{{- if or .Values.webhook.enable .Values.metrics.enable }}
# Service for webhook traffic
apiVersion: v1
kind: Service
metadata:
  name: pac-quota-controller-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pac-quota-controller
    control-plane: controller-manager
spec:
  ports:
    {{- if .Values.webhook.enable }}
    - port: 443
      protocol: TCP
      targetPort: 9443
      name: webhook-server
    {{- end }}
    {{- if .Values.metrics.enable }}
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    app.kubernetes.io/name: pac-quota-controller
    control-plane: controller-manager
{{- end }}
