apiVersion: v2
name: pac-quota-controller
description: A Helm chart for PAC Quota Controller - Managing cluster resource quotas across namespaces
type: application
version: 4.0.0
appVersion: "4.0.1"
maintainers:
  - name: PowerHome
    url: https://github.com/powerhome
home: https://github.com/powerhome/pac-quota-controller
sources:
  - https://github.com/powerhome/pac-quota-controller
keywords:
  - kubernetes
  - quota
  - resource-management
