# To integrate with Prometheus.
{{- if .Values.prometheus.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: pac-quota-controller-manager-monitor
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - path: /metrics
      port: metrics-server
      scheme: {{ if .Values.metrics.secure }}https{{ else }}http{{ end }}
      {{- if .Values.metrics.secure }}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        {{- if .Values.certmanager.enable }}
        serverName: pac-quota-controller-webhook-service.{{ .Release.Namespace }}.svc
        insecureSkipVerify: false
        ca:
          secret:
            name: metrics-server-cert
            key: ca.crt
        cert:
          secret:
            name: metrics-server-cert
            key: tls.crt
        keySecret:
          name: metrics-server-cert
          key: tls.key
        {{- else }}
        insecureSkipVerify: true
        {{- end }}
      {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: pac-quota-controller
      control-plane: controller-manager
{{- end }}
